meta_name: "Flip It!"
meta_title: "Flip It!"
meta_description: "Unite Musicians - Create, Remix, and Showcase!"
meta_image: "Meta_FlipIt1.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"
